import { execFileSync } from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { GetTsStringFromFileList } from "../src/config2ts";

const reg = /[\t\r\f\n\s]*/g;

// Write a CSV whose first column is an EnumIndex (key) so every row is a
// distinct object literal type, which is what large tables look like in
// practice.
function writeRowCsv(csvPath: string, rowCount: number): void {
  const lines = ["Key,Text", "EnumIndex,String"];
  for (let i = 0; i < rowCount; i++) {
    lines.push(`id${i},text${i}`);
  }
  fs.writeFileSync(csvPath, lines.join("\n"));
}

test("config2ts merge csv file list", function () {
  const generated = ("// Auto Generated by config2ts, DO NOT EDIT\n\n" + GetTsStringFromFileList([
    "./config/a-user.csv",
    "./config/data.csv",
    "./config/enum-index.csv",
    "./config/ini-file.ini",
    "./config/lang-en.csv",
    "./config/lang-zh.csv",
    "./config/no-id.csv",
    "./config/skill.csv",
    "./config/skilllevel.csv",
    "./config/toml_file.toml",
    "./config/unit.csv",
    "./config/z-base.csv",
  ])).replace(reg, "");
  const fileContent = fs.readFileSync("./config/total.ts").toString().replace(reg, "");
  expect(generated).toBe(fileContent);
});

// A quoted CSV cell may legitimately span multiple lines (e.g. one effect per
// line). Line feeds are the entry separator and must be preserved; CRLF/CR
// should only be normalized to LF, never stripped.
test("multiline quoted cell keeps LF line breaks (CRLF normalized to LF)", function () {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "config2ts-"));
  const csvPath = path.join(tmpDir, "multi.csv");
  // Effects cell: LF-separated entries on row 1, CRLF-separated on row 2.
  fs.writeFileSync(
    csvPath,
    [
      "Name,Effects",
      "String,String",
      '"a","+1 Max HP\n+2 Armor"',
      '"b","+3 Luck\r\n+4 Speed\r"',
    ].join("\n"),
  );
  const generated = GetTsStringFromFileList([csvPath]);
  // LF separators must survive so downstream can split lines into entries.
  expect(generated).toContain("'+1 Max HP\\n+2 Armor'");
  // CRLF/CR are normalized to LF (entries stay separated), not concatenated.
  expect(generated).toContain("'+3 Luck\\n+4 Speed'");
  expect(generated).not.toContain("HP+2");
  expect(generated).not.toContain("Luck+4");
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

// One object literal per row means a big table would build one very large
// array literal, which makes tsc bail out with ts(2590) ("Expression produces a
// union type that is too complex to represent"). The EnumIndex (key) field is
// what makes every row a distinct type, so for large tables that field falls
// back to string and the array literal union collapses.
test("large table falls EnumIndex field back to string", function () {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "config2ts-"));
  const csvPath = path.join(tmpDir, "big.csv");
  writeRowCsv(csvPath, 1200);

  const generated = GetTsStringFromFileList([csvPath]);
  // The EnumIndex key field is downgraded to string in Record...
  expect(generated).toContain("    export interface Record {");
  expect(generated).toContain("        Key: string;");
  expect(generated).not.toContain("        Key: Key;");
  // ...while List stays a single plain literal (no chunking) and the key union
  // / keyList are still emitted.
  expect(generated).not.toContain("ListChunk");
  expect(generated).toContain("    export type Key = ");
  expect(generated).toContain("    export const KeyList: Key[] = [");
  expect((generated.match(/^        \{/gm) ?? []).length).toBe(1200);

  const smallCsvPath = path.join(tmpDir, "small.csv");
  writeRowCsv(smallCsvPath, 3);
  const small = GetTsStringFromFileList([smallCsvPath]);
  expect(small).toContain("        Key: Key;");
  expect(small).not.toContain("Key: string;");
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

// The regression this guards against is a compiler limit, so it can only be
// observed by actually running tsc on the generated file.
test("large table output compiles without ts(2590)", function () {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "config2ts-"));
  const csvPath = path.join(tmpDir, "big.csv");
  writeRowCsv(csvPath, 1200);
  const tsPath = path.join(tmpDir, "big.ts");
  fs.writeFileSync(tsPath, GetTsStringFromFileList([csvPath]));

  const tscPath = path.join(__dirname, "../node_modules/typescript/bin/tsc");
  let failed = false;
  let output = "";
  try {
    execFileSync(process.execPath, [tscPath, "--noEmit", "--skipLibCheck", "--target", "ES2021", "--module", "ES2022", tsPath], { encoding: "utf-8" });
  } catch (e: any) {
    failed = true;
    output = `${e.stdout ?? ""}${e.stderr ?? ""}${e.message ?? ""}`;
  }
  expect(output).not.toContain("2590");
  expect(failed).toBe(false);
  fs.rmSync(tmpDir, { recursive: true, force: true });
}, 120000);
