// Auto Generated by config2ts, DO NOT EDIT

import { ZBaseCsv } from "./z-base";

export namespace AUserCsv {

    export interface Record {
        id: string;
        base: ZBaseCsv.Record;
    };

    export const List: Record[] = [
        {
            id: '1',
            base: ZBaseCsv.Map["z1"],
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
