// Auto Generated by config2ts, DO NOT EDIT

export namespace DataCsv {

    export type mytype = "type1" | "type2" | "";
    export const mytypeList: mytype[] = ["type1", "type2", ""];

    export type typearray = "t1" | "t2" | "t3" | "t4";
    export const typearrayList: typearray[] = ["t1", "t2", "t3", "t4"];

    export type obj = {
        num?: number;
        str?: string;
        bool?: boolean;
    };

    export type objarray = {
        num?: number;
        str?: string;
        bool?: boolean;
    };

    export interface Record {
        id: string;
        name: string;
        bool: boolean;
        num: number;
        mytype: mytype;
        stringarray: string[];
        numberarray: number[];
        typearray: typearray[];
        'space field/sub': string;
        obj: obj;
        objarray: objarray[];
    };

    export const List: Record[] = [
        {
            id: '1',
            name: 'xxx',
            bool: true,
            num: 111,
            mytype: 'type1',
            stringarray: ['1','2','3'],
            numberarray: [1,2,3],
            typearray: ['t1'],
            'space field/sub': 'a',
            obj: {num:1,str:'ab'},
            objarray: [{num:1,str:'a'},{num:2}],
        },
        {
            id: '2',
            name: 'xxx',
            bool: false,
            num: 222,
            mytype: 'type2',
            stringarray: ['a','b'],
            numberarray: [],
            typearray: ['t1','t2'],
            'space field/sub': 'a',
            obj: {str:'hello',num:2},
            objarray: [{str:'hi'},{},{bool:true}],
        },
        {
            id: '3',
            name: '333',
            bool: false,
            num: NaN,
            mytype: '',
            stringarray: [],
            numberarray: [1,2],
            typearray: ['t2','t3','t4'],
            'space field/sub': 'b',
            obj: {},
            objarray: [{},{}],
        },
        {
            id: '4',
            name: '444',
            bool: true,
            num: Infinity,
            mytype: 'type2',
            stringarray: ['','1','','b'],
            numberarray: [0,1,0,3],
            typearray: [],
            'space field/sub': 'c',
            obj: {num:4,bool:true,str:'test'},
            objarray: [{num:4,bool:false}],
        },
        {
            id: '5',
            name: '555',
            bool: true,
            num: 555,
            mytype: 'type1',
            stringarray: ['a','b'],
            numberarray: [1,2],
            typearray: ['t3'],
            'space field/sub': 'c',
            obj: {num:1,str:'m'},
            objarray: [{num:1},{num:2}],
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
