// Auto Generated by config2ts, DO NOT EDIT

export namespace LangEnCsv {

    export interface Record {
        id: string;
        text: string;
    };

    export const List: Record[] = [
        {
            id: 'skill.101.name',
            text: 'Fireball',
        },
        {
            id: 'skill.101.desc',
            text: 'Deals {damage} fire damage to an enemy within {range}m.',
        },
        {
            id: 'skill.102.name',
            text: 'Heal',
        },
        {
            id: 'skill.102.desc',
            text: 'Restores {heal} HP to a friendly target.',
        },
        {
            id: 'skill.103.name',
            text: 'Lightning',
        },
        {
            id: 'skill.103.desc',
            text: 'Deals {damage} thunder damage, chaining up to {chain} targets.',
        },
        {
            id: 'unit.1.name',
            text: 'Hero One',
        },
        {
            id: 'unit.1.desc',
            text: 'A brave hero.\nCharges into battle first.',
        },
        {
            id: 'unit.2.name',
            text: 'Hero Two',
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
