// Auto Generated by config2ts, DO NOT EDIT

export namespace LangZhCsv {

    export interface Record {
        id: string;
        text: string;
    };

    export const List: Record[] = [
        {
            id: 'skill.101.name',
            text: '火球术',
        },
        {
            id: 'skill.101.desc',
            text: '对 {range} 米内的敌人造成 {damage} 点火焰伤害。',
        },
        {
            id: 'skill.102.name',
            text: '治疗术',
        },
        {
            id: 'skill.102.desc',
            text: '为友方目标恢复 {heal} 点生命值。',
        },
        {
            id: 'skill.103.name',
            text: '闪电链',
        },
        {
            id: 'skill.103.desc',
            text: '造成 {damage} 点雷电伤害，最多连锁 {chain} 个目标。',
        },
        {
            id: 'unit.1.name',
            text: '英雄一号',
        },
        {
            id: 'unit.1.desc',
            text: '勇敢的英雄。\n总是率先冲锋。',
        },
        {
            id: 'unit.2.name',
            text: '英雄二号',
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
