// Auto Generated by config2ts, DO NOT EDIT

import { DataCsv } from "./data";
import { EnumIndexCsv } from "./enum-index";

export namespace NoIdCsv {

    export interface Record {
        name: string;
        bool: boolean;
        num: number;
        dataRecord: DataCsv.Record;
        myType: DataCsv.mytype;
        typeArr: DataCsv.typearray[];
        enumIndexRecord: EnumIndexCsv.Record;
        recordArr: DataCsv.Record[];
        tpl: DataCsv.Record;
        tplArr: DataCsv.Record[];
    };

    export const List: Record[] = [
        {
            name: 'xxx',
            bool: true,
            num: 111,
            dataRecord: DataCsv.Map["1"],
            myType: 'type1',
            typeArr: ['t1','t2'],
            enumIndexRecord: EnumIndexCsv.Map["111"],
            recordArr: [DataCsv.Map["1"],DataCsv.Map["2"]],
            tpl: {...DataCsv.Map["1"],num:999,numberarray:[10,20]},
            tplArr: [{...DataCsv.Map["1"],num:10,bool:true},{...DataCsv.Map["2"],name:'yyy',stringarray:['p','q']}],
        },
        {
            name: 'xxx',
            bool: false,
            num: 222,
            dataRecord: DataCsv.Map["2"],
            myType: 'type2',
            typeArr: [],
            enumIndexRecord: EnumIndexCsv.Map["222"],
            recordArr: [],
            tpl: {...DataCsv.Map["2"],mytype:'type2',obj:{str:'hi',num:9}},
            tplArr: [{...DataCsv.Map["3"],mytype:'type2',obj:{str:'hi',num:9}}],
        },
        {
            name: '333',
            bool: false,
            num: 0,
            dataRecord: DataCsv.Map[""],
            myType: '',
            typeArr: [],
            enumIndexRecord: EnumIndexCsv.Map["333"],
            recordArr: [DataCsv.Map["3"]],
            tpl: {...DataCsv.Map["4"],name:'zzz'},
            tplArr: [DataCsv.Map["4"]],
        }
    ];

};
