// Auto Generated by config2ts, DO NOT EDIT

import { SkillCsv } from "./skill";

export namespace SkilllevelCsv {

    export interface Record {
        id: string;
        skill: SkillCsv.Record;
        level: number;
        damage: number;
        heal: number;
        manaCost: number;
    };

    export const List: Record[] = [
        {
            id: '1',
            skill: SkillCsv.Map["101"],
            level: 1,
            damage: 100,
            heal: 0,
            manaCost: 20,
        },
        {
            id: '2',
            skill: SkillCsv.Map["101"],
            level: 2,
            damage: 150,
            heal: 0,
            manaCost: 30,
        },
        {
            id: '3',
            skill: SkillCsv.Map["102"],
            level: 1,
            damage: 0,
            heal: 200,
            manaCost: 40,
        },
        {
            id: '4',
            skill: SkillCsv.Map["103"],
            level: 1,
            damage: 80,
            heal: 0,
            manaCost: 25,
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
