// Auto Generated by config2ts, DO NOT EDIT

export namespace SkillCsv {

    export type kind = "attack" | "support";
    export const kindList: kind[] = ["attack", "support"];

    export type params = {
        damage?: number;
        range?: number;
        element?: string;
        heal?: number;
        target?: string;
        chain?: number;
    };

    export interface Record {
        id: string;
        name: string;
        kind: kind;
        params: params;
    };

    export const List: Record[] = [
        {
            id: '101',
            name: 'fireball',
            kind: 'attack',
            params: {damage:100,range:5,element:'fire'},
        },
        {
            id: '102',
            name: 'heal',
            kind: 'support',
            params: {heal:200,target:'ally'},
        },
        {
            id: '103',
            name: 'lightning',
            kind: 'attack',
            params: {damage:80,range:3,element:'thunder',chain:3},
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
