// Auto Generated by config2ts, DO NOT EDIT

import { SkillCsv } from "./skill";

export namespace UnitCsv {

    export interface Record {
        id: string;
        name: string;
        skills: SkillCsv.Record[];
    };

    export const List: Record[] = [
        {
            id: '1',
            name: 'hero1',
            skills: [SkillCsv.Map["101"],SkillCsv.Map["102"]],
        },
        {
            id: '2',
            name: 'hero2',
            skills: [SkillCsv.Map["103"]],
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
