// Auto Generated by config2ts, DO NOT EDIT

export namespace ZBaseCsv {

    export interface Record {
        id: string;
        name: string;
    };

    export const List: Record[] = [
        {
            id: 'z1',
            name: 'base-one',
        },
        {
            id: 'z2',
            name: 'base-two',
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};
