"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Convert = void 0;
exports.assets2ts = assets2ts;
exports.GetTsString = GetTsString;
exports.GetTsStringFromFileList = GetTsStringFromFileList;
exports.GetValidFileList = GetValidFileList;
exports.startConvert = startConvert;
const path = __importStar(require("path"));
const fs = __importStar(require("fs"));
const d3_dsv_1 = require("d3-dsv");
const json5 = __importStar(require("json5"));
const changeCase = __importStar(require("change-case"));
const toml = __importStar(require("toml"));
const EnumStr = "Enum";
const EnumIndexStr = "EnumIndex";
const EnumArrayString = "Enum[]";
const IndexStr = "Index";
const ObjectStr = "Object";
const ObjectArrayString = "Object[]";
const RefPrefix = "Ref[";
const RefSuffix = "]";
const RefEnumPrefix = "RefEnum[";
const RefEnumArraySuffix = "][]";
const AutoGenHeader = "// Auto Generated by config2ts, DO NOT EDIT\n\n";
exports.Convert = {
    ini: function (str, moduleName) {
        const obj = toml.parse(str);
        return `export const ${moduleName} = ${json5.stringify(obj, null, 4)};`;
    },
    csv: function (str, moduleName) {
        return csv2ts(str, moduleName);
    },
    toml: function (str, moduleName) {
        const obj = toml.parse(str);
        return `export const ${moduleName} = ${json5.stringify(obj, null, 4)};`;
    },
};
function csv2ts(csvString, moduleName) {
    let convert = {};
    const refFields = [];
    const refEnumFields = [];
    const result = (0, d3_dsv_1.csvParse)(csvString, function (d, i) {
        if (i === 0) {
            convert = d;
            for (const k in convert) {
                if (parseRef(convert[k])) {
                    refFields.push(k);
                }
                if (parseRefEnum(convert[k])) {
                    refEnumFields.push(k);
                }
                if (!isKnownType(convert[k])) {
                    console.warn(`[config2ts] warning: ${moduleName} field "${k}" has unrecognized type "${convert[k]}", values will be treated as string`);
                }
            }
            return null;
        }
        else {
            for (const k in d) {
                d[k] = normalizeCell(d[k]);
                if (convert[k] === ObjectStr) {
                    d[k] = parseObject(d[k]);
                }
                else if (convert[k] === ObjectArrayString) {
                    d[k] = parseObjectArray(d[k]);
                }
                else if (typeof global[convert[k]] === "function") {
                    d[k] = global[convert[k]](d[k]);
                }
                else if (convert[k] === "String[]" || convert[k] === "Enum[]") {
                    d[k] = splitStringArray(d[k]);
                }
                else if (convert[k] === "Number[]") {
                    d[k] = splitStringArray(d[k]).map((val) => Number(val));
                }
                else if (parseRef(convert[k])) {
                    const ref = parseRef(convert[k]);
                    if (ref.isArray) {
                        const ids = splitStringArray(d[k]);
                        d[k] = ids;
                        if (ids.includes("")) {
                            console.warn(`[config2ts] warning: ${moduleName} row ${i} field "${k}" ref array contains an empty id`);
                        }
                    }
                    else if (d[k] === "") {
                        console.warn(`[config2ts] warning: ${moduleName} row ${i} field "${k}" ref value is empty`);
                    }
                }
                else if (parseRefEnum(convert[k])) {
                    const refEnum = parseRefEnum(convert[k]);
                    if (refEnum.isArray) {
                        d[k] = splitStringArray(d[k]);
                    }
                    else {
                        if (d[k] === "") {
                            console.warn(`[config2ts] warning: ${moduleName} row ${i} field "${k}" ref enum value is empty`);
                        }
                    }
                }
                else {
                    d[k] = String(d[k]);
                }
            }
            return d;
        }
    });
    delete result.columns;
    if (result.length <= 0) {
        return "";
    }
    let template = `export namespace ${moduleName} {\n\n`;
    for (const field in convert) {
        if (convert[field] == EnumStr || convert[field] == EnumIndexStr) {
            const enumValues = [];
            for (const row of result) {
                const enumValue = row[field];
                if (!enumValues.includes(enumValue)) {
                    enumValues.push(enumValue);
                }
            }
            const enumValueStrings = enumValues.map((value) => `"${value}"`);
            template += `    export type ${field} = ${enumValueStrings.join(" | ")};\n`;
            template += `    export const ${field}List: ${field}[] = [${enumValueStrings.join(", ")}];\n\n`;
        }
        else if (convert[field] == EnumArrayString) {
            const enumValues = [];
            for (const row of result) {
                const enumArrayValue = row[field];
                for (const enumValue of enumArrayValue) {
                    if (!enumValues.includes(enumValue)) {
                        enumValues.push(enumValue);
                    }
                }
            }
            const enumValueStrings = enumValues.map((value) => `"${value}"`);
            template += `    export type ${field} = ${enumValueStrings.join(" | ")};\n`;
            template += `    export const ${field}List: ${field}[] = [${enumValueStrings.join(", ")}];\n\n`;
        }
        else if (convert[field] == ObjectStr || convert[field] == ObjectArrayString) {
            const keyTypes = {};
            const isArray = convert[field] == ObjectArrayString;
            for (const row of result) {
                const objValues = isArray ? row[field] : [row[field]];
                for (const objValue of objValues) {
                    for (const key in objValue) {
                        if (!keyTypes[key]) {
                            keyTypes[key] = new Set();
                        }
                        keyTypes[key].add(getTypeName(objValue[key]));
                    }
                }
            }
            template += `    export type ${field} = {\n`;
            for (const key in keyTypes) {
                const types = Array.from(keyTypes[key]).join(" | ");
                template += `        ${serializeField(key)}?: ${types};\n`;
            }
            template += `    };\n\n`;
        }
    }
    template += "    export interface Record {\n";
    let indexField = null;
    for (const field in convert) {
        let fieldType = "string";
        if (convert[field] != "") {
            if (convert[field] == EnumStr) {
                fieldType = field;
            }
            else if (convert[field] == EnumIndexStr) {
                fieldType = field;
                indexField = field;
            }
            else if (convert[field] == IndexStr) {
                indexField = field;
            }
            else if (convert[field] == EnumArrayString) {
                fieldType = field + "[]";
            }
            else if (convert[field] == ObjectStr) {
                fieldType = field;
            }
            else if (convert[field] == ObjectArrayString) {
                fieldType = field + "[]";
            }
            else if (parseRef(convert[field])) {
                const ref = parseRef(convert[field]);
                const refModuleName = changeCase.pascalCase(ref.refModule);
                fieldType = ref.isArray ? `${refModuleName}.Record[]` : `${refModuleName}.Record`;
            }
            else if (parseRefEnum(convert[field])) {
                const refEnum = parseRefEnum(convert[field]);
                const refModuleName = changeCase.pascalCase(refEnum.refModule);
                fieldType = refEnum.isArray ? `${refModuleName}.${refEnum.refField}[]` : `${refModuleName}.${refEnum.refField}`;
            }
            else {
                fieldType = convert[field].toLowerCase();
            }
        }
        const serializedField = serializeField(field);
        template += `        ${serializedField}: ${fieldType};\n`;
    }
    template += "    };\n\n";
    if (indexField) {
        const filteredResult = result.filter((v) => {
            return v[indexField] !== "";
        });
        for (let i = 0; i < filteredResult.length; i++) {
            result[i] = filteredResult[i];
        }
        result.length = filteredResult.length;
    }
    template += "    export const List: Record[] = [\n";
    for (let i = 0; i < result.length; i++) {
        const row = result[i];
        template += "        {\n";
        for (const field in convert) {
            let value = row[field];
            if (parseRef(convert[field])) {
                const ref = parseRef(convert[field]);
                const refModuleName = changeCase.pascalCase(ref.refModule);
                if (ref.isArray) {
                    const refs = value.map((id) => `${refModuleName}.Map[${JSON.stringify(id)}]`).join(",");
                    template += `            ${serializeField(field)}: [${refs}],\n`;
                }
                else {
                    template += `            ${serializeField(field)}: ${refModuleName}.Map[${JSON.stringify(value)}],\n`;
                }
            }
            else {
                template += `            ${serializeField(field)}: ${json5.stringify(value)},\n`;
            }
        }
        template += "        }";
        if (i < result.length - 1) {
            template += ",";
        }
        template += "\n";
    }
    template += "    ];\n\n";
    if (indexField != null) {
        template += "    export const Map: { [id: string]: Record } = {};\n";
        template += `    for (const v of List) { Map[v.${indexField}] = v; };\n\n`;
    }
    template += "};";
    return template;
}
function serializeField(key) {
    const obj = {};
    obj[key] = true;
    const objString = json5.stringify(obj);
    return objString.includes("'") ? "'" + key + "'" : key;
}
function parseObject(str) {
    const result = {};
    const trimmed = str.trim();
    if (trimmed === "") {
        return result;
    }
    const pairs = trimmed.split(",");
    for (const pair of pairs) {
        const colonIndex = pair.indexOf(":");
        if (colonIndex > 0) {
            const key = pair.slice(0, colonIndex).trim();
            const value = pair.slice(colonIndex + 1).trim();
            result[key] = parseObjectValue(value);
        }
    }
    return result;
}
// Normalize a raw cell value: drop line-break artifacts (e.g. Excel/CSV \r\n)
// and surrounding whitespace so all downstream parsing sees clean text.
function normalizeCell(str) {
    return String(str).replace(/\r\n?|\n/g, "").trim();
}
// Split a comma-separated primitive-array cell: n commas make n+1 slots and every
// slot is kept (including an interior or trailing empty one), so parallel arrays
// stay index-aligned. Empty slots follow the element's own parsing rule
// ('' for strings/enums, 0 for numbers); null is never emitted.
// An empty cell resolves to an empty array.
// Note: Object[] uses semicolons as element separator (see parseObjectArray),
// because commas already separate key:value pairs inside an object.
function splitStringArray(str) {
    if (str === "") {
        return [];
    }
    return str.split(",").map((v) => v.trim());
}
// Object[] separates objects with semicolons (commas are reserved for the
// key:value pairs inside an object, same syntax as the Object type); each
// semicolon slot is parsed by the same object rule, so stray empty pairs within
// an object (e.g. "num:1,,str:a") are ignored while an empty object slot between
// semicolons (e.g. "a:1;;b:2") becomes an empty object placeholder.
function parseObjectArray(str) {
    if (str === "") {
        return [];
    }
    return str.split(";").map((part) => parseObject(part));
}
function parseObjectValue(value) {
    if (value === "true")
        return true;
    if (value === "false")
        return false;
    if (value === "")
        return "";
    const num = Number(value);
    if (!isNaN(num)) {
        return num;
    }
    return value;
}
function getTypeName(value) {
    if (typeof value === "number")
        return "number";
    if (typeof value === "boolean")
        return "boolean";
    return "string";
}
function isKnownType(typeStr) {
    if (typeStr === "") {
        return true;
    }
    const knownTypes = [EnumStr, EnumIndexStr, EnumArrayString, IndexStr, ObjectStr, ObjectArrayString, "String[]", "Number[]"];
    if (knownTypes.includes(typeStr)) {
        return true;
    }
    if (parseRef(typeStr)) {
        return true;
    }
    if (parseRefEnum(typeStr)) {
        return true;
    }
    if (typeof global[typeStr] === "function") {
        return true;
    }
    return false;
}
// Parse Ref[module] (single) and Ref[module][] (array of row references).
// Note: "RefEnum[...]" starts with "RefE", so it never collides with "Ref[".
function parseRef(typeStr) {
    if (!typeStr.startsWith(RefPrefix)) {
        return null;
    }
    let isArray = false;
    let inner = typeStr;
    if (typeStr.endsWith(RefEnumArraySuffix)) {
        isArray = true;
        inner = typeStr.slice(0, -RefEnumArraySuffix.length) + RefSuffix;
    }
    if (inner.startsWith(RefPrefix) && inner.endsWith(RefSuffix)) {
        const refModule = inner.slice(RefPrefix.length, -RefSuffix.length);
        if (refModule !== "") {
            return { refModule, isArray };
        }
    }
    return null;
}
function parseRefEnum(typeStr) {
    if (typeStr.startsWith(RefEnumPrefix)) {
        let isArray = false;
        let inner = typeStr;
        if (typeStr.endsWith(RefEnumArraySuffix)) {
            isArray = true;
            inner = typeStr.slice(0, -RefEnumArraySuffix.length) + RefSuffix;
        }
        if (inner.endsWith(RefSuffix)) {
            const content = inner.slice(RefEnumPrefix.length, -RefSuffix.length);
            const dotIndex = content.lastIndexOf(".");
            if (dotIndex > 0) {
                const refModule = content.slice(0, dotIndex);
                const refField = content.slice(dotIndex + 1);
                return { refModule, refField, isArray };
            }
        }
    }
    return null;
}
function GetFileExt(filePath) {
    const pathObject = path.parse(filePath);
    return pathObject.ext.slice(1);
}
function scanDir(dir, basePath) {
    const node = {};
    let hasContent = false;
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            const key = entry.name;
            const childNode = scanDir(fullPath, path.posix.join(basePath, entry.name));
            if (childNode !== null) {
                node[key] = childNode;
                hasContent = true;
            }
        }
        else if (entry.isFile()) {
            const parsed = path.parse(entry.name);
            const ext = parsed.ext.slice(1).toLowerCase();
            const key = parsed.name;
            const relPath = path.posix.join(basePath, entry.name);
            node[key] = { path: relPath, type: ext };
            hasContent = true;
        }
    }
    return hasContent ? node : null;
}
function isLeafNode(value) {
    return "path" in value && "type" in value;
}
function getUniformType(node) {
    const values = Object.values(node);
    if (values.length <= 1)
        return null;
    let uniformType = null;
    for (const v of values) {
        if (!isLeafNode(v))
            return null;
        if (uniformType === null) {
            uniformType = v.type;
        }
        else if (uniformType !== v.type) {
            return null;
        }
    }
    return uniformType;
}
function collectUniformDirs(node, dirTypes, exts) {
    const ut = getUniformType(node);
    if (ut !== null) {
        dirTypes.set(node, ut);
        exts.add(ut);
        return;
    }
    for (const v of Object.values(node)) {
        if (!isLeafNode(v)) {
            collectUniformDirs(v, dirTypes, exts);
        }
    }
}
function extToTypeName(ext) {
    return ext.charAt(0).toUpperCase() + ext.slice(1) + "Asset";
}
function serializeAssetNode(node, indent, uniformDirs, extTypeMap) {
    const entries = Object.entries(node);
    if (entries.length === 0)
        return `${indent}{}`;
    const ut = uniformDirs.get(node);
    const lines = [];
    for (let i = 0; i < entries.length; i++) {
        const [key, value] = entries[i];
        const serializedKey = serializeField(key);
        const comma = i < entries.length - 1 ? "," : "";
        if (isLeafNode(value)) {
            lines.push(`${indent}${serializedKey}: {path:${json5.stringify(value.path)},type:${json5.stringify(value.type)}}${comma}`);
        }
        else {
            const childUt = uniformDirs.get(value);
            const typeAnnotation = childUt ? ` satisfies Record<string, ${extTypeMap.get(childUt)}>` : "";
            lines.push(`${indent}${serializedKey}: {`);
            lines.push(serializeAssetNode(value, indent + "    ", uniformDirs, extTypeMap));
            lines.push(`${indent}}${typeAnnotation}${comma}`);
        }
    }
    return lines.join("\n");
}
function assets2ts(assetsDir) {
    if (!fs.existsSync(assetsDir)) {
        return "";
    }
    const dirName = path.basename(assetsDir);
    const root = scanDir(assetsDir, dirName);
    if (root === null) {
        return "";
    }
    const uniformDirs = new Map();
    const exts = new Set();
    collectUniformDirs(root, uniformDirs, exts);
    const extTypeMap = new Map();
    const sortedExts = Array.from(exts).sort();
    for (const ext of sortedExts) {
        extTypeMap.set(ext, extToTypeName(ext));
    }
    let template = "";
    for (const ext of sortedExts) {
        const typeName = extTypeMap.get(ext);
        template += `export type ${typeName} = { path: string; type: ${json5.stringify(ext)} };\n`;
    }
    if (sortedExts.length > 0)
        template += "\n";
    template += `export const ASSETS = {\n`;
    const rootUt = uniformDirs.get(root);
    template += `    ${dirName}: {\n`;
    template += serializeAssetNode(root, "        ", uniformDirs, extTypeMap);
    const rootAnnotation = rootUt ? ` satisfies Record<string, ${extTypeMap.get(rootUt)}>` : "";
    template += `\n    }${rootAnnotation}\n`;
    template += `};\n`;
    return template;
}
function GetTsString(filePath) {
    const pathObject = path.parse(filePath);
    const handle = exports.Convert[GetFileExt(filePath)];
    if (handle) {
        const moduleName = changeCase.pascalCase(pathObject.base);
        let fileString = fs.readFileSync(filePath).toString();
        if (fileString.charAt(0) === "\uFEFF")
            fileString = fileString.substr(1);
        return handle(fileString, moduleName);
    }
    else {
        return "";
    }
}
function GetTsStringFromFileList(fileList) {
    return fileList
        .map(function (filePath) {
        return GetTsString(filePath);
    })
        .join("\n\n");
}
function GetValidFileList(fileList) {
    return fileList.filter(function (filePath) {
        return exports.Convert[GetFileExt(filePath)] != null;
    });
}
function startConvert(dir, outDir, merge, assetsDir) {
    const fileList = fs.readdirSync(dir);
    const fullFileList = GetValidFileList(fileList).map(function (filename) {
        return path.join(dir, filename);
    });
    const mergeFile = path.join(outDir, merge);
    fs.writeFileSync(mergeFile, AutoGenHeader + GetTsStringFromFileList(fullFileList), { encoding: "utf-8" });
    console.log(`config2ts, ${fullFileList.length} config files, merge into: ${mergeFile}`);
    if (assetsDir) {
        const assetsOutput = assets2ts(assetsDir);
        if (assetsOutput) {
            const assetsFile = path.join(outDir, "assets.ts");
            fs.writeFileSync(assetsFile, AutoGenHeader + assetsOutput, { encoding: "utf-8" });
            console.log(`assets2ts, resource dir: ${assetsDir}, output: ${assetsFile}`);
        }
    }
}
