// Auto Generated by config2ts, DO NOT EDIT

export namespace DataCsv {

    export type mytype = "type1" | "type2" | "";
    export const mytypeList: mytype[] = ["type1", "type2", ""];

    export type typearray = "t1" | "t2" | "t3" | "t4";
    export const typearrayList: typearray[] = ["t1", "t2", "t3", "t4"];

    export type obj = {
        num?: number;
        str?: string;
        bool?: boolean;
    };

    export type objarray = {
        num?: number;
        str?: string;
        bool?: boolean;
    };

    export interface Record {
        id: string;
        name: string;
        bool: boolean;
        num: number;
        mytype: mytype;
        stringarray: string[];
        numberarray: number[];
        typearray: typearray[];
        'space field/sub': string;
        obj: obj;
        objarray: objarray[];
    };

    export const List: Record[] = [
        {
            id: '1',
            name: 'xxx',
            bool: true,
            num: 111,
            mytype: 'type1',
            stringarray: ['1','2','3'],
            numberarray: [1,2,3],
            typearray: ['t1'],
            'space field/sub': 'a',
            obj: {num:1,str:'ab'},
            objarray: [{num:1,str:'a'},{num:2}],
        },
        {
            id: '2',
            name: 'xxx',
            bool: false,
            num: 222,
            mytype: 'type2',
            stringarray: ['a','b'],
            numberarray: [],
            typearray: ['t1','t2'],
            'space field/sub': 'a',
            obj: {str:'hello',num:2},
            objarray: [{str:'hi'},{},{bool:true}],
        },
        {
            id: '3',
            name: '333',
            bool: false,
            num: NaN,
            mytype: '',
            stringarray: [],
            numberarray: [1,2],
            typearray: ['t2','t3','t4'],
            'space field/sub': 'b',
            obj: {},
            objarray: [{},{}],
        },
        {
            id: '4',
            name: '444',
            bool: true,
            num: Infinity,
            mytype: 'type2',
            stringarray: ['','1','','b'],
            numberarray: [0,1,0,3],
            typearray: [],
            'space field/sub': 'c',
            obj: {num:4,bool:true,str:'test'},
            objarray: [{num:4,bool:false}],
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};

export namespace EnumIndexCsv {

    export type name = "111" | "222" | "333";
    export const nameList: name[] = ["111", "222", "333"];

    export interface Record {
        name: name;
        bool: boolean;
        num: number;
    };

    export const List: Record[] = [
        {
            name: '111',
            bool: true,
            num: 111,
        },
        {
            name: '222',
            bool: false,
            num: 222,
        },
        {
            name: '333',
            bool: false,
            num: 0,
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.name] = v; };

};

export const IniFileIni = {
    num: 1,
    str: 'string',
    bool: true,
    ItemType: {
        book: 1,
        fruit: 2,
    },
};

export namespace LangEnCsv {

    export interface Record {
        id: string;
        text: string;
    };

    export const List: Record[] = [
        {
            id: 'skill.101.name',
            text: 'Fireball',
        },
        {
            id: 'skill.101.desc',
            text: 'Deals {damage} fire damage to an enemy within {range}m.',
        },
        {
            id: 'skill.102.name',
            text: 'Heal',
        },
        {
            id: 'skill.102.desc',
            text: 'Restores {heal} HP to a friendly target.',
        },
        {
            id: 'skill.103.name',
            text: 'Lightning',
        },
        {
            id: 'skill.103.desc',
            text: 'Deals {damage} thunder damage, chaining up to {chain} targets.',
        },
        {
            id: 'unit.1.name',
            text: 'Hero One',
        },
        {
            id: 'unit.2.name',
            text: 'Hero Two',
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};

export namespace LangZhCsv {

    export interface Record {
        id: string;
        text: string;
    };

    export const List: Record[] = [
        {
            id: 'skill.101.name',
            text: '火球术',
        },
        {
            id: 'skill.101.desc',
            text: '对 {range} 米内的敌人造成 {damage} 点火焰伤害。',
        },
        {
            id: 'skill.102.name',
            text: '治疗术',
        },
        {
            id: 'skill.102.desc',
            text: '为友方目标恢复 {heal} 点生命值。',
        },
        {
            id: 'skill.103.name',
            text: '闪电链',
        },
        {
            id: 'skill.103.desc',
            text: '造成 {damage} 点雷电伤害，最多连锁 {chain} 个目标。',
        },
        {
            id: 'unit.1.name',
            text: '英雄一号',
        },
        {
            id: 'unit.2.name',
            text: '英雄二号',
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};

export namespace NoIdCsv {

    export interface Record {
        name: string;
        bool: boolean;
        num: number;
        dataRecord: DataCsv.Record;
        myType: DataCsv.mytype;
        typeArr: DataCsv.typearray[];
        enumIndexRecord: EnumIndexCsv.Record;
        recordArr: DataCsv.Record[];
        tpl: DataCsv.Record;
        tplArr: DataCsv.Record[];
    };

    export const List: Record[] = [
        {
            name: 'xxx',
            bool: true,
            num: 111,
            dataRecord: DataCsv.Map["1"],
            myType: 'type1',
            typeArr: ['t1','t2'],
            enumIndexRecord: EnumIndexCsv.Map["111"],
            recordArr: [DataCsv.Map["1"],DataCsv.Map["2"]],
            tpl: {...DataCsv.Map["1"],num:999,bool:true},
            tplArr: [{...DataCsv.Map["1"],num:10,bool:true},{...DataCsv.Map["2"],name:'yyy'}],
        },
        {
            name: 'xxx',
            bool: false,
            num: 222,
            dataRecord: DataCsv.Map["2"],
            myType: 'type2',
            typeArr: [],
            enumIndexRecord: EnumIndexCsv.Map["222"],
            recordArr: [],
            tpl: DataCsv.Map["2"],
            tplArr: [{...DataCsv.Map["3"],mytype:'type2'}],
        },
        {
            name: '333',
            bool: false,
            num: 0,
            dataRecord: DataCsv.Map[""],
            myType: '',
            typeArr: [],
            enumIndexRecord: EnumIndexCsv.Map["333"],
            recordArr: [DataCsv.Map["3"]],
            tpl: {...DataCsv.Map["4"],name:'zzz'},
            tplArr: [DataCsv.Map["4"]],
        }
    ];

};

export namespace SkillCsv {

    export type kind = "attack" | "support";
    export const kindList: kind[] = ["attack", "support"];

    export type params = {
        damage?: number;
        range?: number;
        element?: string;
        heal?: number;
        target?: string;
        chain?: number;
    };

    export interface Record {
        id: string;
        name: string;
        kind: kind;
        params: params;
    };

    export const List: Record[] = [
        {
            id: '101',
            name: 'fireball',
            kind: 'attack',
            params: {damage:100,range:5,element:'fire'},
        },
        {
            id: '102',
            name: 'heal',
            kind: 'support',
            params: {heal:200,target:'ally'},
        },
        {
            id: '103',
            name: 'lightning',
            kind: 'attack',
            params: {damage:80,range:3,element:'thunder',chain:3},
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};

export namespace SkilllevelCsv {

    export interface Record {
        id: string;
        skill: SkillCsv.Record;
        level: number;
        damage: number;
        heal: number;
        manaCost: number;
    };

    export const List: Record[] = [
        {
            id: '1',
            skill: SkillCsv.Map["101"],
            level: 1,
            damage: 100,
            heal: 0,
            manaCost: 20,
        },
        {
            id: '2',
            skill: SkillCsv.Map["101"],
            level: 2,
            damage: 150,
            heal: 0,
            manaCost: 30,
        },
        {
            id: '3',
            skill: SkillCsv.Map["102"],
            level: 1,
            damage: 0,
            heal: 200,
            manaCost: 40,
        },
        {
            id: '4',
            skill: SkillCsv.Map["103"],
            level: 1,
            damage: 80,
            heal: 0,
            manaCost: 25,
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};

export const TomlFileToml = {
    num: 1,
    str: 'test',
    ItemType: {
        book: 1,
        fruit: 2,
    },
};

export namespace UnitCsv {

    export interface Record {
        id: string;
        name: string;
        skills: SkillCsv.Record[];
    };

    export const List: Record[] = [
        {
            id: '1',
            name: 'hero1',
            skills: [SkillCsv.Map["101"],SkillCsv.Map["102"]],
        },
        {
            id: '2',
            name: 'hero2',
            skills: [SkillCsv.Map["103"]],
        }
    ];

    export const Map: { [id: string]: Record } = {};
    for (const v of List) { Map[v.id] = v; };

};